sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - cppcheck
    - valgrind
    - lcov
install:
- "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make clean
  - make
  - make cov
  - make test_cov
  - make test_cpp
  - make test_valgrind
  - make test_sanitize
  - make unity_array
  - make run_unity_tests